site_name: My Docs
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
  - https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css 
  - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css
theme:
  name: material
  language: en 
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github  
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    # - content.code.annotate
    - navigation.expand
    # - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
nav:
  # - Home: index.md
  # - Internals:
  #   - Overview: overview.md
  #   - Configuration Properties: configuration-properties.md
  #   - KubernetesClusterManager: KubernetesClusterManager.md
  - Home: index.md
  - Portfolio: portfolio.md
  - Portfolio EN: portfolioEn.md
  - Python:
    - Install: python/install.md
    - Pandas: python/pandas.md
    - Seaborn: python/seaborn.md
    - Scikit-learn: python/scikit-learn.md
    - Links: python/links.md
  - Spark:
    - Install: spark/install.md 
    - Optimalization: spark/optimalization.md
  - Other: 
    - Markdown: markdown.md
